# Regenerate the aspell dictionary that clears CRAN's "possibly misspelled words"
# NOTE. Run from the package root:
#
#   Rscript data-raw/aspell.R
#
# These are correct technical terms (package and function names, jargon) that the
# system aspell dictionary does not know. Add one to the vector and re-run to
# accept it. This directory is .Rbuildignore'd, so it does not ship in the tarball;
# the generated .aspell/ does, and CRAN's incoming check reads it.
words <- c(
  "backends",
  "ggplot",
  "gpaint"
)

dir.create(".aspell", showWarnings = FALSE)
saveRDS(sort(unique(words)), ".aspell/words.rds")
writeLines(
  c(
    "# Generated by data-raw/aspell.R. R CMD check --as-cran reads this file to",
    "# accept the words in .aspell/words.rds during its spelling pass.",
    "Rd_files <- vignettes <- R_files <- description <-",
    '  list(encoding = "UTF-8", dictionaries = c("en_stats", "words"))'
  ),
  ".aspell/defaults.R"
)
